global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'document-service'

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  # Document service metrics
  - job_name: 'document-service'
    static_configs:
      - targets: ['app:8001']
    scrape_interval: 5s
    metrics_path: /metrics
    scrape_timeout: 10s

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 10s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 10s

  # Node/system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 10s

  # RabbitMQ metrics
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    scrape_interval: 10s

  # MinIO metrics
  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
    scrape_interval: 10s
    metrics_path: /minio/v2/metrics/cluster

  # ClamAV metrics (if available)
  - job_name: 'clamav'
    static_configs:
      - targets: ['clamav:9090']
    scrape_interval: 30s

  # Nginx metrics (if available)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    scrape_interval: 10s

  # Jaeger metrics
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']
    scrape_interval: 10s

  # Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 10s
    metrics_path: /metrics

# Recording rules
recording_rules:
  - name: document_service_rules
    rules:
      - record: document_service:request_rate
        expr: rate(http_requests_total[5m])
      
      - record: document_service:error_rate
        expr: rate(http_requests_total{status=~"5.."}[5m])
      
      - record: document_service:response_time_95th
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))
      
      - record: document_service:cpu_usage
        expr: rate(process_cpu_seconds_total[5m])
      
      - record: document_service:memory_usage
        expr: process_resident_memory_bytes