apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    basicAuth: false
    editable: true
    jsonData:
      timeInterval: 30s
      queryTimeout: 60s
      httpMethod: POST
      manageAlerts: true
      alertmanagerUid: alertmanager
    secureJsonData: {}

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    isDefault: false
    basicAuth: false
    editable: true
    jsonData:
      nodeGraph:
        enabled: true
    secureJsonData: {}

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    basicAuth: false
    editable: true
    jsonData:
      maxLines: 1000
      timeout: 60s
      derivedFields:
        - datasourceUid: jaeger
          matcherRegex: '"trace_id":"([^"]+)"'
          name: TraceID
          url: '$${__value.raw}'
          urlDisplayLabel: 'View Trace'
    secureJsonData: {}

  - name: Alertmanager
    type: alertmanager
    access: proxy
    url: http://alertmanager:9093
    isDefault: false
    basicAuth: false
    editable: true
    jsonData:
      implementation: prometheus
      handleGrafanaManagedAlerts: true
    secureJsonData: {}